AWSTemplateFormatVersion: '2010-09-09'
Description: 'Basic CloudFront Distribution with S3 Origin'

Resources:
  DistributionExample:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultCacheBehavior:
          TargetOriginId: myS3Origin
          ViewerProtocolPolicy: redirect-to-https
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
        Origins:
          - DomainName: !Sub '${S3Bucket}.s3.amazonaws.com'
            Id: myS3Origin
            S3OriginConfig:
              OriginAccessIdentity: ''

  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub '${AWS::StackName}-content'
