AWSTemplateFormatVersion: 2010-09-09
#### DESCRIPTION #################################################################################################################################################################################################
Description: >-
  Template basico de una rds mysql

Parameters:
  DBInstanceIdentifier:
    Type: String
    Default: 'db-example'
  DBUsername:
    NoEcho: 'true'
    Description: Username for Mysql database access
    Type: String
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: Must begin with a letter and contain only alphanumeric characters.
    Default: 'usrexample'
  DBPassword:
    NoEcho: 'true'
    Description: Password Mysql database access
    Type: String
    MinLength: '8'
    MaxLength: '20'
    AllowedPattern: '[a-zA-Z0-9]*'
    ConstraintDescription: Must contain only alphanumeric characters.

Resources:     
  DatabaseMysql:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Ref DBInstanceIdentifier
      AllocatedStorage: '5'
      DBInstanceClass: db.t3.micro
      Engine: mysql
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      VpcSecurityGroups:
        - !Ref MysqlDBSecurityGroup
      BackupRetentionPeriod: 30
      DBInstanceAutomatedBackupType: automated
      PreferredBackupWindow: "04:00-05:00"
      StorageEncrypted: true
      Tags:
        - Key: Name
          Value: db-example-mysql
  
  MysqlDBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group para mysql
      SecurityGroupEgress:
        - IpProtocol: "-1"
          CidrIp: "0.0.0.0/0"
      SecurityGroupIngress:
        - Description: Acceso desde internet
          IpProtocol: tcp
          CidrIp: "0.0.0.0/0"
          FromPort: 3306
          ToPort: 3306

Outputs:
  WebAppDatabaseEndpoint:
    Description: 'Connection endpoint for the database'
    Value: !GetAtt DatabaseMysql.Endpoint.Address