AWSTemplateFormatVersion: '2010-09-09'
Description: 'Basic S3 Read-Only Access Policy'

Parameters:
  BucketName:
    Type: String
    Description: Name of the S3 bucket

Resources:
  S3ReadOnlyPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Allows read-only access to S3 buckets
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: 
              - s3:GetObject
              - s3:ListBucket
            Resource: 
              - !Sub 'arn:aws:s3:::${BucketName}'
              - !Sub 'arn:aws:s3:::${BucketName}/*'