AWSTemplateFormatVersion: '2010-09-09'
Description: 'Developer Access Policy'

Parameters:
  DevBucket:
    Type: String
  TableName:
    Type: String

Resources:
  DeveloperPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Developer access to common services
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - s3:GetObject
              - s3:PutObject
              - s3:ListBucket
            Resource:
              - !Sub 'arn:aws:s3:::${DevBucket}/*'
              - !Sub 'arn:aws:s3:::${DevBucket}'
          
          - Effect: Allow
            Action:
              - dynamodb:Query
              - dynamodb:Scan
              - dynamodb:GetItem
              - dynamodb:PutItem
            Resource: !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${TableName}'
          
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/developer/*'
